# Generated by Django 4.0.5 on 2022-06-06 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instagram', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.CharField(blank=True, max_length=50, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.CharField(blank=True, max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
